version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "3000"
    volumes:
      - sdc:/var/lib/postgresql/data
    env_file:
      - ./env/backend.env
    depends_on:
      - "psql"
  psql:
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - sdc:/var/lib/postgresql/data
    env_file:
      - ./env/psql.env
volumes:
  sdc: